# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               Adriel's Dev Blog
tagline:             'Eat, Sleep, Code, Repeat...'
description:         'An effort to capture some of the beauty of coding with a collection of words, images, and charts.'
url:                 http://adrielklein.github.io/dev-blog
baseurl:             ''
paginate:            1
repo:            https://github.com/adrielklein/dev-blog

# About/contact
author:
  name:              Adriel Klein
  url:               http://adrielklein.github.io
  email:             adrielmklein@gmail.com

# Custom vars
version:             1.0.0

gems: [jekyll-paginate]
